/* 
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using Flagr.Api.Client;
using Flagr.Api.Model;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

namespace Flagr.Api.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial interface IDistributionApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>List&lt;Distribution&gt;</returns>
        List<Distribution> FindDistributions_GET (long? flagID, long? segmentID);

        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>ApiResponse of List&lt;Distribution&gt;</returns>
        ApiResponse<List<Distribution>> FindDistributions_GETWithHttpInfo (long? flagID, long? segmentID);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>List&lt;Distribution&gt;</returns>
        List<Distribution> PutDistributions_PUT (long? flagID, long? segmentID, PutDistributionsRequest body);

        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>ApiResponse of List&lt;Distribution&gt;</returns>
        ApiResponse<List<Distribution>> PutDistributions_PUTWithHttpInfo (long? flagID, long? segmentID, PutDistributionsRequest body);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>Task of List&lt;Distribution&gt;</returns>
        System.Threading.Tasks.Task<List<Distribution>> FindDistributions_GETAsync (long? flagID, long? segmentID);

        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>Task of ApiResponse (List&lt;Distribution&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Distribution>>> FindDistributions_GETAsyncWithHttpInfo (long? flagID, long? segmentID);
        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>Task of List&lt;Distribution&gt;</returns>
        System.Threading.Tasks.Task<List<Distribution>> PutDistributions_PUTAsync (long? flagID, long? segmentID, PutDistributionsRequest body);

        /// <summary>
        /// 
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>Task of ApiResponse (List&lt;Distribution&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Distribution>>> PutDistributions_PUTAsyncWithHttpInfo (long? flagID, long? segmentID, PutDistributionsRequest body);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    [ExcludeFromCodeCoverage]
    public partial class DistributionApi : IDistributionApi
    {
        private Flagr.Api.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DistributionApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DistributionApi(string basePath)
        {
            Configuration = new Flagr.Api.Client.Configuration { BasePath = basePath };

            ExceptionFactory = Flagr.Api.Client.Configuration.DefaultExceptionFactory;

            Configuration.ApiClient.Configuration = Configuration.ApiClient.Configuration ?? Configuration;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DistributionApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DistributionApi(Flagr.Api.Client.Configuration configuration = null)
        {
            Configuration = configuration ?? Flagr.Api.Client.Configuration.Default;

            ExceptionFactory = Flagr.Api.Client.Configuration.DefaultExceptionFactory;

            Configuration.ApiClient.Configuration = Configuration.ApiClient.Configuration ?? Configuration;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.ApiClient.RestClient.BaseUrl != null ? Configuration.ApiClient.RestClient.BaseUrl.ToString() : string.Empty;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Flagr.Api.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Flagr.Api.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set => _exceptionFactory = value;
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<string, string> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>List&lt;Distribution&gt;</returns>
        public List<Distribution> FindDistributions_GET (long? flagID, long? segmentID)
        {
            ApiResponse<List<Distribution>> response = FindDistributions_GETWithHttpInfo(flagID, segmentID);
            if(response.StatusCode >= 400)
                throw new ApiException (response.StatusCode, "Error calling FindDistributions_GET: " + response.Data, response.Data);
            if (response.StatusCode == 0)
                throw new ApiException (response.StatusCode, "Error calling FindDistributions_GET: " + response.Headers, response.Headers);
            return response.Data;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>ApiResponse of List&lt;Distribution&gt;</returns>
        public ApiResponse< List<Distribution> > FindDistributions_GETWithHttpInfo (long? flagID, long? segmentID)
        {
            // verify the required parameter 'flagID' is set
            if (flagID == null)
                throw new ApiException(400, "Missing required parameter 'flagID' when calling DistributionApi->FindDistributions_GET");
            // verify the required parameter 'segmentID' is set
            if (segmentID == null)
                throw new ApiException(400, "Missing required parameter 'segmentID' when calling DistributionApi->FindDistributions_GET");

            const string localVarPath = "./flags/{flagID}/segments/{segmentID}/distributions";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (flagID != null) localVarPathParams.Add("flagID", this.Configuration.ApiClient.ParameterToString(flagID)); // path parameter
            if (segmentID != null) localVarPathParams.Add("segmentID", this.Configuration.ApiClient.ParameterToString(segmentID)); // path parameter


            // make the HTTP request
            var localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            List<Distribution> resultingObject;
            string swaggerResponseMessage = null;

            try
            {
                resultingObject = (List<Distribution>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Distribution>));
            }
            catch
            {
                resultingObject = null;
                swaggerResponseMessage = localVarResponse.Content;
            }

            var apiResponse = new ApiResponse<List<Distribution>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value?.ToString()),
                resultingObject,
                swaggerResponseMessage);
            return apiResponse;
        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>Task of List&lt;Distribution&gt;</returns>
        public async System.Threading.Tasks.Task<List<Distribution>> FindDistributions_GETAsync (long? flagID, long? segmentID)
        {
            ApiResponse<List<Distribution>> response = await FindDistributions_GETAsyncWithHttpInfo(flagID, segmentID);
            if(response.StatusCode >= 400)
                throw new ApiException(response.StatusCode, "Error calling FindDistributions_GET: " + response.Data, response.Data);
            if (response.StatusCode == 0)
                throw new ApiException(response.StatusCode, "Error calling FindDistributions_GET: " + response.Headers, response.Headers);
            return response.Data;

        }

        /// <summary>
        ///  
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <returns>Task of ApiResponse (List&lt;Distribution&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Distribution>>> FindDistributions_GETAsyncWithHttpInfo (long? flagID, long? segmentID)
        {
            // verify the required parameter 'flagID' is set
            if (flagID == null)
                throw new ApiException(400, "Missing required parameter 'flagID' when calling DistributionApi->FindDistributions_GET");
            // verify the required parameter 'segmentID' is set
            if (segmentID == null)
                throw new ApiException(400, "Missing required parameter 'segmentID' when calling DistributionApi->FindDistributions_GET");

            var localVarPath = "./flags/{flagID}/segments/{segmentID}/distributions";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (flagID != null) localVarPathParams.Add("flagID", this.Configuration.ApiClient.ParameterToString(flagID)); // path parameter
            if (segmentID != null) localVarPathParams.Add("segmentID", this.Configuration.ApiClient.ParameterToString(segmentID)); // path parameter


            // make the HTTP request
            var localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            List<Distribution> resultingObject;
            string swaggerResponseMessage = null;

            try
            {
                resultingObject = (List<Distribution>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Distribution>));
            }
            catch
            {
                resultingObject = null;
                swaggerResponseMessage = localVarResponse.Content;
            }

            var apiResponse = new ApiResponse<List<Distribution>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value?.ToString()),
                resultingObject,
                swaggerResponseMessage);
            return apiResponse;
        }
        
        /// <summary>
        ///  replace the distribution with the new setting
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>List&lt;Distribution&gt;</returns>
        public List<Distribution> PutDistributions_PUT (long? flagID, long? segmentID, PutDistributionsRequest body)
        {
            ApiResponse<List<Distribution>> response = PutDistributions_PUTWithHttpInfo(flagID, segmentID, body);
            if(response.StatusCode >= 400)
                throw new ApiException (response.StatusCode, "Error calling PutDistributions_PUT: " + response.Data, response.Data);
            if (response.StatusCode == 0)
                throw new ApiException (response.StatusCode, "Error calling PutDistributions_PUT: " + response.Headers, response.Headers);
            return response.Data;
        }

        /// <summary>
        ///  replace the distribution with the new setting
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>ApiResponse of List&lt;Distribution&gt;</returns>
        public ApiResponse< List<Distribution> > PutDistributions_PUTWithHttpInfo (long? flagID, long? segmentID, PutDistributionsRequest body)
        {
            // verify the required parameter 'flagID' is set
            if (flagID == null)
                throw new ApiException(400, "Missing required parameter 'flagID' when calling DistributionApi->PutDistributions_PUT");
            // verify the required parameter 'segmentID' is set
            if (segmentID == null)
                throw new ApiException(400, "Missing required parameter 'segmentID' when calling DistributionApi->PutDistributions_PUT");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DistributionApi->PutDistributions_PUT");

            const string localVarPath = "./flags/{flagID}/segments/{segmentID}/distributions";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (flagID != null) localVarPathParams.Add("flagID", this.Configuration.ApiClient.ParameterToString(flagID)); // path parameter
            if (segmentID != null) localVarPathParams.Add("segmentID", this.Configuration.ApiClient.ParameterToString(segmentID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            var localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            List<Distribution> resultingObject;
            string swaggerResponseMessage = null;

            try
            {
                resultingObject = (List<Distribution>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Distribution>));
            }
            catch
            {
                resultingObject = null;
                swaggerResponseMessage = localVarResponse.Content;
            }

            var apiResponse = new ApiResponse<List<Distribution>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value?.ToString()),
                resultingObject,
                swaggerResponseMessage);
            return apiResponse;
        }

        /// <summary>
        ///  replace the distribution with the new setting
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>Task of List&lt;Distribution&gt;</returns>
        public async System.Threading.Tasks.Task<List<Distribution>> PutDistributions_PUTAsync (long? flagID, long? segmentID, PutDistributionsRequest body)
        {
            ApiResponse<List<Distribution>> response = await PutDistributions_PUTAsyncWithHttpInfo(flagID, segmentID, body);
            if(response.StatusCode >= 400)
                throw new ApiException(response.StatusCode, "Error calling PutDistributions_PUT: " + response.Data, response.Data);
            if (response.StatusCode == 0)
                throw new ApiException(response.StatusCode, "Error calling PutDistributions_PUT: " + response.Headers, response.Headers);
            return response.Data;

        }

        /// <summary>
        ///  replace the distribution with the new setting
        /// </summary>
        /// <exception cref="Flagr.Api.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="flagID">numeric ID of the flag</param>
        /// <param name="segmentID">numeric ID of the segment</param>
        /// <param name="body">array of distributions</param>
        /// <returns>Task of ApiResponse (List&lt;Distribution&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Distribution>>> PutDistributions_PUTAsyncWithHttpInfo (long? flagID, long? segmentID, PutDistributionsRequest body)
        {
            // verify the required parameter 'flagID' is set
            if (flagID == null)
                throw new ApiException(400, "Missing required parameter 'flagID' when calling DistributionApi->PutDistributions_PUT");
            // verify the required parameter 'segmentID' is set
            if (segmentID == null)
                throw new ApiException(400, "Missing required parameter 'segmentID' when calling DistributionApi->PutDistributions_PUT");
            // verify the required parameter 'body' is set
            if (body == null)
                throw new ApiException(400, "Missing required parameter 'body' when calling DistributionApi->PutDistributions_PUT");

            var localVarPath = "./flags/{flagID}/segments/{segmentID}/distributions";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
                "application/json"
            };
            string localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json"
            };
            string localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (flagID != null) localVarPathParams.Add("flagID", this.Configuration.ApiClient.ParameterToString(flagID)); // path parameter
            if (segmentID != null) localVarPathParams.Add("segmentID", this.Configuration.ApiClient.ParameterToString(segmentID)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            var localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            List<Distribution> resultingObject;
            string swaggerResponseMessage = null;

            try
            {
                resultingObject = (List<Distribution>)this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Distribution>));
            }
            catch
            {
                resultingObject = null;
                swaggerResponseMessage = localVarResponse.Content;
            }

            var apiResponse = new ApiResponse<List<Distribution>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value?.ToString()),
                resultingObject,
                swaggerResponseMessage);
            return apiResponse;
        }
        
    }
}
