/* 
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Flagr.Api.Client.SwaggerDateConverter;

namespace Flagr.Api.Model
{
    /// <summary>
    /// PutSegmentReorderRequest
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DataContract]
    public partial class PutSegmentReorderRequest :  IEquatable<PutSegmentReorderRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutSegmentReorderRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutSegmentReorderRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutSegmentReorderRequest" /> class.
        /// </summary>
        /// <param name="segmentIDs">segmentIDs (required).</param>
        public PutSegmentReorderRequest(List<long?> segmentIDs = default(List<long?>))
        {
            // to ensure "segmentIDs" is required (not null)
            if (segmentIDs == null)
            {
                throw new InvalidDataException("segmentIDs is a required property for PutSegmentReorderRequest and cannot be null");
            }
            else
            {
                this.SegmentIDs = segmentIDs;
            }
        }
        
        /// <summary>
        /// Gets or Sets SegmentIDs
        /// </summary>
        [DataMember(Name="segmentIDs", EmitDefaultValue=false)]
        public List<long?> SegmentIDs { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PutSegmentReorderRequest {\n");
            sb.Append("  SegmentIDs: ").Append(SegmentIDs).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PutSegmentReorderRequest);
        }

        /// <summary>
        /// Returns true if PutSegmentReorderRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of PutSegmentReorderRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PutSegmentReorderRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SegmentIDs == input.SegmentIDs ||
                    this.SegmentIDs != null &&
                    this.SegmentIDs.SequenceEqual(input.SegmentIDs)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SegmentIDs != null)
                    hashCode = hashCode * 59 + this.SegmentIDs.GetHashCode();
                return hashCode;
            }
        }
    }

}
