/* 
 * Flagr
 * Flagr is a feature flagging, A/B testing and dynamic configuration microservice. The base path for all the APIs is \"/api/v1\". 
 * OpenAPI spec version: 1.1.12
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics.CodeAnalysis;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = Flagr.Api.Client.SwaggerDateConverter;

namespace Flagr.Api.Model
{
    /// <summary>
    /// SetFlagEnabledRequest
    /// </summary>
    [ExcludeFromCodeCoverage]
    [DataContract]
    public partial class SetFlagEnabledRequest :  IEquatable<SetFlagEnabledRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetFlagEnabledRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SetFlagEnabledRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SetFlagEnabledRequest" /> class.
        /// </summary>
        /// <param name="enabled">enabled (required).</param>
        public SetFlagEnabledRequest(bool? enabled = default(bool?))
        {
            // to ensure "enabled" is required (not null)
            if (enabled == null)
            {
                throw new InvalidDataException("enabled is a required property for SetFlagEnabledRequest and cannot be null");
            }
            else
            {
                this.Enabled = enabled;
            }
        }
        
        /// <summary>
        /// Gets or Sets Enabled
        /// </summary>
        [DataMember(Name="enabled", EmitDefaultValue=false)]
        public bool? Enabled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SetFlagEnabledRequest {\n");
            sb.Append("  Enabled: ").Append(Enabled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SetFlagEnabledRequest);
        }

        /// <summary>
        /// Returns true if SetFlagEnabledRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of SetFlagEnabledRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SetFlagEnabledRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Enabled == input.Enabled ||
                    (this.Enabled != null &&
                    this.Enabled.Equals(input.Enabled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Enabled != null)
                    hashCode = hashCode * 59 + this.Enabled.GetHashCode();
                return hashCode;
            }
        }
    }

}
